from .objaverse_scene_depth_dataset import ObjaverseSceneDepthDataset
from .objaverse_scene_depth_dataset_alpha import ObjaverseSceneDepthAlphaDataset
from .eval_dataset import EvalDataset
from .threedfrontv4.blenderproc_scene_depth import BlenderProcSceneDepthDataset
